% BGSA code v1.0.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“ 'BGSA: Binary Gravitational Search Algorithm', Natural Computation, vol.9, pp.727- 745, 2010."
%
%This function Evaluates the agents. 
function   [fitness]=evaluateF(X,trData,trTargets,testData,testTargets,KFindices)
fitness=[];
[N,dim]=size(X);
% Nd = size(dataSet,1);
% dataSet = dataSet(inds,:);
% labels = labels(inds,:);
for i=1:N 
    L=X(i,:);Fnum=sum(L==1); trData2=trData(:,L==1);testData2=testData(:,L==1); %tr=zeros(1,Nd);
    %calculation of objective function

    if Fnum~=0

       [ fitness(i,1)]=evalute(trData2,trTargets,testData2,testTargets);       
       
    else
        fitness(i,1)=0;
    end
end
   
 
end
%    fitness=(fitnessEFS);

