% BGSA code v1.0.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“ 'BGSA: Binary Gravitational Search Algorithm', Natural Computation, vol.9, pp.727- 745, 2010."
%
% Binary Gravitational Search Algorithm.
function [Fbest,Lbest,BestChart,MeanChart]=NBGSA(N,max_it,ElitistCheck,min_flag,trData,trTargets,testData,testTargets,ItBreak,KFindices)

%V:   Velocity.
%a:   Acceleration.
%M:   Mass.  Ma=Mp=Mi=M;
%m: Dimension of test function.
%n: Dimension of binary search space.
%N:   Number of agents.
%X:   Position of agents. N-by-n matrix.
%R:   Distance between agents in search space.
%[low-up]: Allowable range for search space.
%Rpower: Power of R in eq.2.
 
Rpower=1; 
 
%Allowable range and the dimension of test function.
n=size(trData,2);low=0;up=1;
%random initialization of agents.
X=Binitialization(n,N); 

%create best so far chart and average fitnesses chart.
BestChart=[];MeanChart=[];

V=zeros(N,n); F=0; iteration=0;

while iteration<max_it
    iteration=iteration+1
     
    %Evaluation of agents.
    [fitness]=evaluateF(X,trData,trTargets,testData,testTargets,KFindices); 
    %%%new method
    if iteration>1
        if min_flag==1
            afit=find(fitness>fitnessold);
        else
            afit=find(fitness<fitnessold);
        end
    X(afit,:)=Xold(afit,:);fitness(afit)=fitnessold(afit);
    end
    %%%

    if min_flag==1
    [best best_X]=min(fitness); %minimization.
    else
    [best best_X]=max(fitness); %fitnessCCR(best_X),fitnessE(best_X)%maximization.
    end        
    
    if iteration==1
       Fbest=best;Lbest=X(best_X,:);
    end
    if min_flag==1
      if best<Fbest  %minimization.
       Fbest=best;Lbest=X(best_X,:);
      end
    else 
      if best>Fbest  %maximization
       Fbest=best;Lbest=X(best_X,:);
      end
    end
 %%%%new method
       if iteration~=1
           if Fbest==BestChart(iteration-1)
               F=F+1;
           end
           if Fbest~=BestChart(iteration-1)
               F=0;
           end
       end
 %%%%       
BestChart=[BestChart Fbest];
MeanChart=[MeanChart mean(fitness)];


%Calculation of M. eq.8-12
[M]=massCalculation(fitness,min_flag); 

%Calculation of Gravitational constant. eq.7.
G=NGconstant(iteration,max_it); 

%Calculation of accelaration in the gravitational field. eq.2-4.
a=NGfield(M,X,G,Rpower,ElitistCheck,iteration,max_it);

%%%
Xold=X;fitnessold=fitness;

%Agent movement. new method
[X,V]=NBmove(X,a,V,F);
Fbest,
%%% speed 
    if iteration>ItBreak
           if BestChart(iteration-ItBreak)==BestChart(iteration)
               BestChart(iteration+1:max_it)=BestChart(iteration);MeanChart(iteration+1:max_it)=MeanChart(iteration);
                   iteration=max_it;
           end
    end
%%%%

end %iteration

